# Generated by Django 5.1.6 on 2025-03-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATRON', 'Library Patron'), ('LIBRARIAN', 'Librarian'), ('ADMIN', 'System Admin')], default='PATRON', max_length=10),
        ),
    ]
